<?php


/**
 * Removes some menus by page.
 */
function wpdocs_remove_menus(){
   // get current login user's role
$roles = wp_get_current_user()->roles;
// test role
if( !in_array('client',$roles)){
  return;
  }
  remove_menu_page( 'tools.php' );                  //Tools
  remove_menu_page( 'plugins.php' );                //Plugins
  remove_menu_page( 'themes.php' );                 //Appearance
  remove_menu_page( 'themes.php' );                 //Appearance
  remove_menu_page( 'cptui_main_menu' );            //plug cpt
  remove_menu_page( 'edit.php?post_type=acf-field-group' );            //plug cpt
  remove_submenu_page( 'index.php', 'update-core.php');  // Update 
  
  //remove_menu_page( 'index.php' );                  //Dashboard
  // remove_menu_page( 'jetpack' );                    //Jetpack* 
  // remove_menu_page( 'edit.php' );                   //Posts
  // remove_menu_page( 'upload.php' );                 //Media
  // remove_menu_page( 'edit.php?post_type=page' );    //Pages
  // remove_menu_page( 'edit-comments.php' );          //Comments
  // //remove_menu_page( 'users.php' );                  //Users
  // remove_menu_page( 'options-general.php' );        //Settings
   
}
add_action( 'admin_menu', 'wpdocs_remove_menus' );





function remove_from_admin_bar($wp_admin_bar) {
   // get current login user's role
   $roles = wp_get_current_user()->roles;
   // test role
   if( !in_array('client',$roles)){
     return;
     }
      // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
      $wp_admin_bar->remove_node('si_menu');

      // WordPress Core Items (uncomment to remove)
      $wp_admin_bar->remove_node('updates');
      $wp_admin_bar->remove_node('comments');
      $wp_admin_bar->remove_node('new-content');
      $wp_admin_bar->remove_node('wp-logo');
      // $wp_admin_bar->remove_node('site-name');
      //$wp_admin_bar->remove_node('my-account');
      $wp_admin_bar->remove_node('search');
      $wp_admin_bar->remove_node('customize');
 
}
add_action('admin_bar_menu', 'remove_from_admin_bar', 999);
